dataset_for_classification:
  dataset:
    normal:
      - "../data/feature_records/0_clean_data/converted_subset_normal_data.csv"
    pre_epileptic:
      - "../data/feature_records/0_clean_data/converted_subset_preepileptic_data.csv"
    seizure:
      - "../data/feature_records/0_clean_data/converted_subset_seizures_data.csv"
  use_prepared_dataset:
    enabled: false
    dataset_path: ""
  save_evaluation_metrics_data: true
  n_splits: 5