dataset_for_classification:
  normal:
    - "/data1/feature_record/normal_data.1.csv"
    - "/data1/feature_record/normal_data.2.csv"
    - "/data1/feature_record/normal_data.3.csv"
    - "/data1/feature_record/normal_data.4.csv"
    - "/data1/feature_record/normal_data.5.csv"
    - "/data1/feature_record/normal_data.6.csv"
    - "/data1/feature_record/normal_data.7.csv"
    - "/data1/feature_record/normal_data.8.csv"
  pre_epileptic:
    - "/data1/feature_record/preepileptic_data.csv"
  seizure:
    - "/data1/feature_record/seizure_data.csv"