syntax_analysis:
  grammar_file: "../../data/pcfg/grammar-trained.pcfg"
  input: "../../data/seizure_integrated_all_d2_s4_converted.txt"
  log_intervals: 1000000
  log_path: "../../data/logs/seizure/"
  report_path: "../../data/reports/seizure/"
  serialize_to_files: false
  tree_serialization_path: "../../data/serialized_tree/seizure/"