phase_convert:
  grammar_file: "data/pcfg/grammar.pcfg"
  input: "../data/recurrence_sentence/epileptic_eeg_dataset/normal_integrated_all_d2_s4.txt"
  output: "../../data/epileptic_eeg_dataset/normal_integrated_all_d2_s4_converted.txt"
